### ISSUE TITLE
Shinobi III - Return of the Ninja Master (USA) doesn't work

### ISSUE THREAD

**Issue by cacophony1** [MiSTer-devel/Genesis_MiSTer#1]
When I run a no-intro rom of "Shinobi III - Return of the Ninja Master (USA)" on the latest Genesis_MiSTer core (20181003) it isn't playable. The introduction sort of works but appears very glitchy and once gameplay starts almost nothing is visible. No main character or enemies appear, but you can hear music and see background art.

This is using MiSTer_20180929 and menu_20180902.rbf

I'm using hdmi out with video_mode=8 and forced_scandoubler=1

**Comment by sorgelig** [comment]
Genesis core is far from perfect, so many games won't work. There is no point to list them here yet, as no one will fix it anyway.
Core will be improved time after time when there will be enough info to know what exactly is incorrect and how to fix.

**Comment by cacophony1** [comment]
Maybe put a note in the readme stating that bugs shouldn't be filed yet? Or have a list somewhere for what cores either should or shouldn't have bugs filed?

**Comment by sorgelig** [comment]
Consoles are usually far from perfect and it's already known fact. You may participate the forum and leave the note about non-working games there in respective thread for specific console.
It will be a lot of opened issues if you will open the issue about every non-working game. And as i've told you it probably won't be fixed soon (if ever will) as info about console precise work is very little.
