### ISSUE TITLE
SPDIF Sound are dirty

### ISSUE THREAD

**Issue by emax73** [MiSTer-devel/Genesis_MiSTer#10]
SPDIF Sound are dirty,
where HDMI Sound clean,
Thanks!

**Comment by sorgelig** [comment]
i have no idea why. I didn't touch SPDIF long time already.
From which release it's started?

**Comment by emax73** [comment]
Version 20180609 have clean sound and low volume
Version 20180926 have dirty sound and high or sufficient volume

**Comment by sorgelig** [comment]
Try to reduce sound volume on MiSTer.

**Comment by emax73** [comment]
How I can do it?

**Comment by sorgelig** [comment]
in MiSTer.ini add (or modify):
volumectl=1            ; enable audio volume control by multimedia keys 

then using keyboard with multimedia keys you can increase/decrease/mute audio volume.

**Comment by emax73** [comment]
Solved in Genesis_20181210.rbf Thank you!!!
