### ISSUE TITLE
Sound is worse with this release

### ISSUE THREAD

**Issue by dirtbead** [MiSTer-devel/Genesis_MiSTer#11]
Sonic 2 has terrible sound, the issues were not there on the previous release.

**Comment by sorgelig** [comment]
Be more specific. I've watched the demo and didn't hear anything horrible.

**Comment by dirtbead** [comment]
No problem. I'm using the the World rom the sound issues are on emerald hill and chemical plant, distortion and sound effects not sounding like they did in the previous release.

**Comment by sorgelig** [comment]
by previous release do you mean 20181116?

**Comment by dirtbead** [comment]
That's correct.

**Comment by sorgelig** [comment]
i've adjusted the volumes before 20181116 release. So latest and previous release should sound the same. And what i hear they are really sound the same.

**Comment by dirtbead** [comment]
Sound is much improved with the latest release, some of the tones still sound slightly off to me, but I can put up with that. Thank you.
