### ISSUE TITLE
Alien Soldier slowdown inaccurate + graphic issues

### ISSUE THREAD

**Issue by Aquas77** [MiSTer-devel/Genesis_MiSTer#110]
Slowdown inaccuracy:

Example video on MiSTer: https://clips.twitch.tv/SpicyEsteemedAniseNomNom

Example video on original hardware: https://clips.twitch.tv/BoredFuriousWalletTebowing

~

Graphic issue:

https://clips.twitch.tv/FaithfulDrabAnteaterBrokeBack

I encountered another graphic glitch on the previous boss graphic, but, I was using the Turbo high setting on the core, as well as the sprite limit increased. I did not have these things turned on for the aforementioned slowdown report. 

Not sure if it's valid at this point... but, I'll show it anyway:

https://clips.twitch.tv/RoughTrappedLyrebirdTheThing

**Comment by sorgelig** [comment]
> I encountered another graphic glitch on the previous boss graphic, but, I was using the Turbo high setting on the core, as well as the sprite limit increased. I did not have these things turned on for the aforementioned slowdown report.
> 
> Not sure if it's valid at this point... but, I'll show it anyway:
> 
> https://clips.twitch.tv/RoughTrappedLyrebirdTheThing

Any issues with Turbo On or Sprite Limit increased are not accepted, sorry.

Not sure about original issue - do you mean white bar blinking on the top?

**Comment by Aquas77** [comment]
Apologies on that. And no, the flashing white bar is normal. That indicates a powerful dash is available from having full health.

The issue is the slowdown. Compare the two videos. Original hardware has far less slowdown as seen in the 2nd video versus MiSTer in the first video.

**Comment by James-F2** [comment]
Using CPU benchmark from here: 
[http://www.sega-16.com/forum/showthread.php?30044-Genesis-SEGA-CD-multi-tool-homebrew&highlight=multi-tool](url)
Mister has exactly the same score as the original console.

Can you please share the save file or cheat to reach the boss level for easy testing?

**Comment by Aquas77** [comment]
The boss fight in question is the last of a boss rush of Stage 20. Not sure about invincibility cheat, maybe the MiSTer can use a cheat somehow? But it's probably one of the hardest parts of the game. Probably want to put the difficulty on "SuperEasy" before using the code.

The password for Stage 20 is: 2878

**Comment by James-F2** [comment]
Okay so I used the 2878 code, and some cheats.
I have defeater this boss with zero slowdown.
What version of the core are you using?

![20200110_103910](https://user-images.githubusercontent.com/31185814/72138567-b7803d80-3395-11ea-9fa3-af16944f4227.jpg)

**Comment by SegaSnatcher** [comment]
I just did this on latest release and didn't have any slow down either.

**Comment by Aquas77** [comment]
Okay I updated my genesis core to latest and then turned on SDRAM for ROM Storage, on MiSTer v200101. Things are A-OKAY now. For the record I am using 32mb SDRAM XS1.1 Sorg as well.

**Comment by sorgelig** [comment]
so it seems not an issue anymore.
