### ISSUE TITLE
Game will stuck by activate a Cheat

### ISSUE THREAD

**Issue by graschbaten** [MiSTer-devel/Genesis_MiSTer#111]
with the latest core i can´t enable a cheat (testet with 20 Games) .
the game will stuck and rest the core doesnt work.

I test it without SD RAM

**Comment by sorgelig** [comment]
Just tested with sonic - no problems, cheats work.

**Comment by James-F2** [comment]
I confirm.
For me it freezes with DDR3 + Cheats.

**Comment by James-F2** [comment]
Fixed.
https://github.com/MiSTer-devel/Genesis_MiSTer/commit/1f7f3e52a29b77542561e6624b4413cb5b5edbda
