### ISSUE TITLE
Sprite glitches on Rocket Knight Adventures (U) with SDRAM only

### ISSUE THREAD

**Issue by slightlybeige** [MiSTer-devel/Genesis_MiSTer#113]
When using SDRAM for ROM storage the Konami logo has a flickering stuck part of the green laser line on screen the whole time, the title screen and intro graphic has sparkster flickering and jumping about 32 pixels to the left.

These problems don't appear when using DDR3 for ROM storage.

The 64MB SDRAM I have passes at 150Mhz for over 2 hours and I haven't seen any problems with large NeoGeo roms so I'm not thinking it's the RAM that's bad.

(The same sprite glitching happens with Final Fight CD in the MegaCD core by the way.)

**Comment by James-F2** [comment]
I can't reproduce with 32MB SDRAM.

**Comment by sorgelig** [comment]
i also can't reproduce

**Comment by slightlybeige** [comment]
I reset my mister.ini to the defaults and am just using the HDMI default output. By changing the rom storage option I can make the flickering start and stop in real time. It also happens in gunstar heroes, but not in Sonic & Knuckles.

<img width="1269" alt="rocketknight" src="https://user-images.githubusercontent.com/59672679/72195029-652c3480-3408-11ea-8ea0-6330a322edaa.png">

I tried an older core but that doesn't have the option so I'm guessing it doesn't use SDRAM?

**Comment by sorgelig** [comment]
64MB modules are know to be glitching. Even if they pass memory test they are still unstable and not recommended to use. Use 32MB or 128MB module.

**Comment by slightlybeige** [comment]
I'm not a hardware guy so I have no idea why that would be, but at a guess if it's the 64MB memory modules that are an issue, wouldn't the 128MB where they have 2x 64MBs have the same issue?
Regardless I've ordered a 32MB module for testing.

**Comment by sorgelig** [comment]
128MB uses other PCB with 4 layers.

**Comment by slightlybeige** [comment]
My 32MB arrived and initially it was working without sprite glitches, however this specific module turned out to be a lemon. So I'm happy to conclude this is RAM related and now I'm off to pick fights with ebay sellers.
