### ISSUE TITLE
Hold reset till sync,, for vsync_adjust=2

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#114]
The NES and GBA has something called: "hold reset till sync".

According to @Kitrinx 
> it keeps the core in reset until the video is in the right spot, then releases.
> it prevents resyncing between rom loads

This will prevent video sync loss when selecting a new rom with vsync_adjust=2.
I think it is a must feature for every 8/16bit console core like Genesis, Snes, tgfx16, etc..

My displays takes 4 seconds to resync on rom load,,,, I miss many intro screens. :laughing:

**Comment by sorgelig** [comment]
That's a serious rework which may affect compatibility. While in reset the VDP is in reset too to clear all settings. Reset for FPGA core equals to power off of real console.
Did you see a console providing the video when powered off? I didn't see.
While it's doable, it may bring more bugs.
You want the feel of real console while using FPGA. Here it is ;)

**Comment by James-F2** [comment]
You are right.
Maybe there is some other trick involved?
I think @Kitrinx can clarify what she did with the NES core.

**Comment by James-F2** [comment]
I'm closing this.
According to Kitrinx, NES core keeps generating sync signal during reset so it was easy to implement for NES.
Genesis and SNES do not keep sync between resets.

**Comment by Kitrinx** [comment]
you can keep an external counter on other cores that takes over during reset to achieve the same, but it requires a bit more extra code
