### ISSUE TITLE
Sonic the Hedgehog Title Screen Graphical Glitch

### ISSUE THREAD

**Issue by MJY71** [MiSTer-devel/Genesis_MiSTer#117]
On the Sonic the Hedgehog title screen, after the 'Sonic Team Presents' screen, Sonic appears in front of the 'Sonic the Hedgehog' banner (scrolls by in front of it) instead of behind it in the black border area. When he stops scrolling, his torso and elbows should be behind the banner, not in front of it. No part of that banner should be obscured at any time.

I have tried a few different versions of the ROM, and they all behave the same way. The one I currently have in the set is the one from SmokeMonster's most recent Mega EverDrive pack:

Sonic The Hedgehog (USA, Europe).md (SHA1: 6DDB7DE1E17E7F6CDB88927BD906352030DAA194)

This YouTube video shows what it is doing perfectly. The video shows correct first, then incorrect: https://www.youtube.com/watch?v=uktCEH1xgQo

The same glitch was present on the Sega Smash Pack for the Sega Dreamcast: http://www.thedreamcastjunkyard.co.uk/2016/02/a-quick-look-at-sega-smash-pack.html

**Comment by paulb-nl** [comment]
This is caused by having sprite limit set to high. Change it to normal.

**Comment by MJY71** [comment]
Thank you very much. Sorry.

**Comment by paulb-nl** [comment]
It's good to have it as known issue. Thanks.

**Comment by sorgelig** [comment]
There are already the same closed issues. 
Users enable extra features like turbo or extra sprites and then rush to report the issue... Yeah.. no one else see it..

**Comment by MJY71** [comment]
Not setting everything to default values and testing before reporting was an honest and simple mistake. High sprite limit has been beneficial in several titles with no noticeable adverse effects up to now. I apologize for not checking the closed issues first as well, but if it's a well known issue, it's not particularly well documented. Anyway, thank you for everything you do. I absolutely love this project.
