### ISSUE TITLE
Reset behavior incorrect.

### ISSUE THREAD

**Issue by iequalshane** [MiSTer-devel/Genesis_MiSTer#127]
When you do a soft reset on the Genesis it should only reset the M68k, Z80, and YM2612 but the memory maintains. This is used by a few games like X-Men 1 (unbeatable without it) and X-Men 2 (how you select the starting character). Some other games use this as well, but I don't know to what extent.

I could fix this, and even have a working build, but there was some logic around the reset button that I was afraid to touch without first consulting you. Also, some users have reported this used to work at some point, but I'm not certain.

Mainly, it's this block of code I was afraid of breaking:
```
reg osd_btn = 0;
always @(posedge clk_sys) begin
	integer timeout = 0;
	reg     has_bootrom = 0;
	reg     last_rst = 0;

	if (RESET) last_rst = 0;
	if (status[0]) last_rst = 1;

	if (cart_download & ioctl_wr & status[0]) has_bootrom <= 1;

	if(last_rst & ~status[0]) begin
		osd_btn <= 0;
		if(timeout < 24000000) begin
			timeout <= timeout + 1;
			osd_btn <= ~has_bootrom;
		end
	end
end
```

**Comment by iequalshane** [comment]
I should note that on a real Genesis you could hold the reset button down for longer to do for hard reset, but just loading the ROM again could be an alternative for this behavior.

**Comment by sorgelig** [comment]
so how these games use it?

**Comment by iequalshane** [comment]
They write something to memory then check the values on boot to detect a soft reset. On X-Men 1, after beating Mojo's stage, it writes to memory then tells the player to "reset the computer" as a gimmick. On boot, if the values are set correctly, the game knows the player just beat Mojo's stage. On X-Men 2 it increments a value every frame and reads this value on boot to pick a "random" starting character. Other games rely on it for secrets or preserving user settings or high scores for the duration of a play session.

**Comment by sorgelig** [comment]
ok. i will think how to make it.

**Comment by iequalshane** [comment]
I have a working prototype but I'm not using an OSD option for the test. I just wired a button to the reset signal of the 68k, z80 and ym2616. The VDP isn't reset during a soft reset on real hardware.

**Comment by sorgelig** [comment]
i've just re-checked the code. Reset itself doesn't clear the memory. Only cart downloading clears the RAM.
So basically it should work.

**Comment by iequalshane** [comment]
Hrm, then something else must be getting reset that shouldn't. I can investigate this weekend and report back.

**Comment by iequalshane** [comment]
Okay, tracking one game that's potentially not resetting properly yet. It's a bit unique in that it requires 3 resets in a row to access a secret menu. I'll try to understand what's going exactly.

**Comment by iequalshane** [comment]
I take that back. This was just a user timing issue. You have to reset 3 times very quickly in a row, which was hard but still possible in the OSD. Closing this bug.
