### ISSUE TITLE
TMSS BIOS Option

### ISSUE THREAD

**Issue by retrorepair** [MiSTer-devel/Genesis_MiSTer#131]
I know it doesn't have much function but will support for the option to load the TMSS BIOS be included at some point?

**Comment by sorgelig** [comment]
there is no such plans.
please use forum for discussions.

**Comment by retrorepair** [comment]
For anyone wondering about this, you can add this to your roms folder as boot.bin

It won't load when you load a rom as it should, but it will load on core boot so at least it's there in some capacity.
