### ISSUE TITLE
Phantasy Star Fukkokuban (Japan) doesn't start

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Genesis_MiSTer#135]
It is the first Phantasy Star game on MegaDrive.
Regarding this page wikipedia it was released on 1994 for this console.
https://en.wikipedia.org/wiki/Phantasy_Star_(video_game)

This game doesn't start on Genesis Core with JP mode set.
The sha1sum of the file:
b3ae447dc739256616b44cbd77cb903c9f19e980  Phantasy Star Fukkokuban (Japan)

**Comment by iequalshane** [comment]
If I remember correctly, this game is an SMS game on a Genesis cart using the same chip as the Power Base Converter to map the addresses.

**Comment by sorgelig** [comment]
SMS mode is not supported in Genesis core. So it won't work.
Use SMS core.

**Comment by wwark** [comment]
Thank you for these informations.
I closed this ticket.
