### ISSUE TITLE
Shining Force II graphics error, reset, then corrupted save.

### ISSUE THREAD

**Issue by birdybro** [MiSTer-devel/Genesis_MiSTer#137]
In Shining Force II (USA) I got to just before the 5th battle, right as Lemon and the King of Galam walked downward and the screen would normally pan up. Then the screen looked like it was rapidly being moved around, like in a circle with the center of the screen being the axis. I'm running this on a fairly new 55" TV in the living room.

The menu is not affected however, so it's something within the genesis core. So I do a reset of the console itself. I have autosave turned on. I reload and the game lets me know that my save is lost (the witch at the beginning literally tells you that it's lost). So the save got corrupted somehow, and given the timestamp on the .sav file, it autosaved having recognized the save file being corrupted and it seems to have removed the data. I have attached the save file that is now corrupted in case it at all helps in figuring out what went wrong. The MD5 of the rom I used is:

6473B1505334EF5620D13191C18251FE

**Save File** [Shining Force II (USA).zip](https://github.com/MiSTer-devel/Genesis_MiSTer/files/4874402/Shining.Force.II.USA.zip)

However, I do vaguely remember having seen the corrupt save error before, but it was on a very old cartridge so likely a failing battery. It's also possible this is just a bug in the game itself that can happen. Figured I'd report it as I have not seen that behavior in other Genesis games yet.

I am using the 128mb SDRAM (from misterfpga.co.uk) with release 20200701 of the Genesis core. Attached hardware are just an 8bitdo receiver, asus ac53 nano wifi, 8bitdo m30 bluetooth, and HDMI to my Denon receiver, to my tv, etc... Using the USB hub 1.2 and Analog I/O XL 6.1 both from misterfpga.co.uk.

To see the precise part of the game the bug occurred, here's someone who speedran the game, 24 minutes on his timer is where it happened to me (and obviously not them).

https://www.twitch.tv/videos/44235340

 The soldiers are walking down and the screen pans up. Right at this time to accomplish this the devs must have defied the collision rules for walls or something, and I wonder if that has something to do with it.

**Comment by aberusugi** [comment]
Likely was a coincidence that it happened the same time as the error. It's possible it could be related to autosaving overwriting the save file on rom load during a quick reset prior to loading the save as outlined in the SNES pull request here. 

https://github.com/MiSTer-devel/SNES_MiSTer/pull/225

**Comment by birdybro** [comment]
@paulb-nl checked the Genesis code and determined that the core's save code is not the root cause. I think it's likely this was either some kind of user error on my part or a glitch inherent to the game itself. Closing as it's very likely not a real issue with the core.
