### ISSUE TITLE
Lotus II Recs Music 

### ISSUE THREAD

**Issue by worleydl** [MiSTer-devel/Genesis_MiSTer#14]
There seems to be a timing issue in this game as the music doesn't always play correctly.

The title screen should begin playing "Track 4" which is hit or miss. If you go to start a race it presents a dashboard where you can switch between the audio tracks.  Sometimes the tracks play as expected, other times there is silence or "noise" where it sounds like it's playing things that are in memory but the wrong address.

**Comment by jotego** [comment]
As a side note: I check the MiST version and this bug was not present.

**Comment by worleydl** [comment]
Fixed in https://github.com/MiSTer-devel/Genesis_MiSTer/blob/master/releases/Genesis_20190407.rbf
