### ISSUE TITLE
Sonic The Hedgehog (US) - No parallax scroll in "sky" background layer

### ISSUE THREAD

**Issue by jegayon** [MiSTer-devel/Genesis_MiSTer#152]
There's not parallax scroll in background layer. The clouds apears like unique layer scrolling together.

Thx very much for you effort.

**Comment by jegayon** [comment]
Sorry...I have a mistake. I've been playing the Dreamcast version of Sonic the Hedgehog Collection too much and got confused.
:/

**Comment by hmusta** [comment]
I think only the third Japanese edition of Sonic the Hedgehog (the same ROM was used in the Dreamcast collection) had a scrolling background.
