### ISSUE TITLE
Hyokkori Hyoutanjima (J) bin/md doesn't respond.

### ISSUE THREAD

**Issue by Hareluya79** [MiSTer-devel/Genesis_MiSTer#154]
As per title, pressing doesn't start the game.
The game will just demo all the way, pressing any buttons doesn't do anything.

**Comment by birdybro** [comment]
Using this rom..

https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=0610

I see the same thing. However, something interesting... If you go into Inputs/Swap Joysticks and turn that to on, you can get past the title screen adn the intro, then it gets stuck on the character/controls screen, and it's acting like a direction is being held, maybe right on the d-pad? Weird. I swapped 6-button mode on and off, and nothing changed about this behavior. The direction pad stops being pressed if I change Multitap to "Teamplayer: Port 1" which is interesting as well..

https://segaretro.org/Team_Player

Maybe this device was required for this game, or the game's method of detecting if the Team Player is being used is different than expected? Either way the input mapping is all wrong on this one.

**Comment by iequalshane** [comment]
I got this working on my Genesis core but I'll need to do a bit of cleanup. I'll try to get a PR out tonight or tomorrow.

**Comment by Hareluya79** [comment]
> Using this rom that matches this no-intro db..
> 
> https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=0610
> 
> I see the same thing. However, something interesting... If you go into Inputs/Swap Joysticks and turn that to on, you can get past the title screen and the intro (start works), then it gets stuck on the character/controls screen, and it's acting like a direction is being held, maybe right on the d-pad? Weird. I swapped 6-button mode on and off, and nothing changed about this behavior. The direction pad stops being pressed if I change Multitap to "Teamplayer: Port 1" which is interesting as well..
> 
> https://segaretro.org/Team_Player
> 
> Maybe this device was required for this game, or the game's method of detecting if the Team Player is being used is different than expected? Either way the input mapping is all wrong on this one.
> 
> EDIT: Does the current implementation of the Team Player multitap mode support the "EXTRA" mode built into the 2nd revision? Maybe the game is looking for both controller ports to be occupied by the Team Player, or something like that...

The Game itself supports only 1 controller on original hardware, I tested the exact same rom on Genesis 1 with Everdrive X7 and Mega SD too~ Hope it can be rectified soon~ :D

**Comment by iequalshane** [comment]
I fixed the issue already. The pull request is in review.

**Comment by Hareluya79** [comment]
> I got this working on my Genesis core but I'll need to do a bit of cleanup. I'll try to get a PR out tonight or tomorrow.

Thank you sir for the swift response~ 👍
