### ISSUE TITLE
Ghouls and ghosts MSU MD is freezing randomly on MiSTer

### ISSUE THREAD

**Issue by thehughhefner** [MiSTer-devel/Genesis_MiSTer#164]
Referring to the following msu MD hack https://github.com/ArcadeTV/msu-md-ghoulsnghosts/releases/tag/v1.0

The game freezes randomly during gameplay on the MiSTer.

**Comment by birdybro** [comment]
I thought msu md would only work on the MegaCD core, where you have to place a "cart.rom" in the enhanced cd folder and load with MegaCD.

**Comment by iequalshane** [comment]
This is in the wrong repo. I'll post a bug in MegaCD.

**Comment by jotego** [comment]
The issue can be transferred to a different repository by clicking on "transfer issue". I don't know if any user can transfer issues, though.

**Comment by iequalshane** [comment]
Ah, good to know for the future. I added the new issue already https://github.com/MiSTer-devel/MegaCD_MiSTer/issues/61
