### ISSUE TITLE
Titan Overdrive II Demo compatibility

### ISSUE THREAD

**Issue by badvision** [MiSTer-devel/Genesis_MiSTer#168]
Demo: https://www.pouet.net/prod.php?which=69648

This demo by Titan is a monster and uses a lot of creative tricks and undocumented video registers to pull off some insane results.  You're going to have to remind yourself this is coming out of a Genesis and not a Saturn.  Plus the rom is loaded with large audio samples driving an insane music track.  That being said, this demo is a notorious emulator-killer.   The credits at the end offers places where you can get grief counseling if your emulator broke.

And the verdict is that this core impressively handles this demo.  The only parts that are problematic are:
1) The region detection doesn't detect EU like it should so you have to manually select the EU region before it will play.
2) In the arcade screen (just before the insane infinite zoom part), the character walks to the right side and destroys the screen borders with a sword.  Because the emulator crops to the center and cuts off borders, you miss this effect.

Everything else plays, and it's spot-on.  Way to go on this core!!!  Keep up the amazing work!

-Brendan

**Comment by sorgelig** [comment]
50% of VDP has been rewritten based on this demo and tech notes released by its developers.
1) i don't have problem with region detection. Probably you has region detection by file extension and ROM has wrong extension.
2) it's known fact. This effect is useless for games and used only in this single demo. So it left as is.

**Comment by badvision** [comment]
You're right -- I didn't have my region detection setting selected correctly.  Thanks for the tip!

Ok so fun fact, when I turn on borders that part of the demo actually shows the top and bottom borders breaking away so it actually works great.

Major kudos for a solid core!  Thanks so much!
