### ISSUE TITLE
Turbo CPU / Sonic 2 (maybe others), game & audio slow down

### ISSUE THREAD

**Issue by teknomedic** [MiSTer-devel/Genesis_MiSTer#169]
Had set Turbo CPU to high, Sonic 2 title screen then had slow down as well as game play.  After setting CPU to normal, all that disappeared.  Haven't tested other games.  Assuming a timing issue of some sort.

**Comment by sorgelig** [comment]
Turbo option is not guaranteed to work correctly with all game, so it cannot be treated as an issue.
It's a bonus which may or may not work. Different parts of game's code may speed-up differently and produce a race condition. Some games may misbehave, some games may crash. Turn off turbo option for these games. Nothing to do here.
