### ISSUE TITLE
mega Turrican end of level bug

### ISSUE THREAD

**Issue by Dal78** [MiSTer-devel/Genesis_MiSTer#17]
When completing a level on mega turrican the crystals are counted at 1 per second rather than summed up within a couple seconds for 100 or so.  I get the feeling the count speed is off by a factor of 50.

See video:
https://photos.app.goo.gl/N5U2DoqtZ5eKHaFF6

Work to the end of the level to see for yourself.  Played on a base Mister with no expansion memory or boards.

**Comment by James-F2** [comment]
Fixed.
I have tested twice to be 100% sure.

**Comment by James-F2** [comment]
Can be closed.
