### ISSUE TITLE
Star Trek: The Next Generation freezes on mission log review

### ISSUE THREAD

**Issue by callanbrown** [MiSTer-devel/Genesis_MiSTer#170]
Hello,

I am trying to play Star Trek The Next Generation (U) and it freezes when I access the mission log. This can be done as soon as you start the game:

Navigate to Computer, press A, navigate to Mission Log, press A, navigate to Review Mission Log, press A, then press A again.

This appears to be the save game function. If you save first (Record Mission Log), it can be Reviewed without crashing.

**Comment by Blitzwing1** [comment]
Tested and confirmed. Will crash when there is no backup ram saved, after saving the backup ram it will load successfully.

Same rom tested in Genesis plus GX and it will display load failed and go back to the "computer" menu.

Does the game play successfully when the backup ram is saved?

**Comment by fedex81** [comment]
I'd guess that genplus gx is filling SRAM with random bytes on creation, while Mister most likely populates it with all 0s.

**Comment by birdybro** [comment]
BlastEm! writes SRAM files the same was the Genesis MiSTer core (they are interchangeable), and this has the same problem (just tested it). Interesting. Still not completely sure if that's the real reason for the problem, but would be interesting if true.

**Comment by Blitzwing1** [comment]
> BlastEm! writes SRAM files the same way the Genesis MiSTer core (they are interchangeable), and this has the same problem (just tested it). Interesting. Still not completely sure if that's the real reason for the problem, but would be interesting if true. Does PicoDrive's SRAM file for the game populate with 0's as well?

Picodrive doesn't write an SRM file when "review mission log is selected" but it does hang like the others. I got exactly the same in Blastem it writes an 8KB file 0x00, gens writes a 64KB 0xFF file and the genesis core a 64KB 0x00 file. It seems gens takes the safer route by filling the sram by default.

**Comment by birdybro** [comment]
The emulators all simulate having SRAM there regardless if they've written a file. The initial SRAM state in the Genesis core should probably be changed to 0xFF to reflect the original spec. This would require a few of the sram_quirks I think to be modified as well...

**Comment by tjanas** [comment]
I tested this on Analogue Mega Sg JB firmware v7.7 and it works fine. It does not freeze. “Load Failed” is displayed briefly, and then returns to Computer.

**Comment by tjanas** [comment]
Also works fine with the Analogue Nt Mini Noir JB.

**Comment by birdybro** [comment]
This is resolved now @callanbrown with the latest commit.

**Comment by IndoJimbo** [comment]
> This is resolved now @callanbrown with the latest commit. No release file yet though.

Great job! I came here to report this exact crash and good to see you already fixed it!

**Comment by birdybro** [comment]
@callanbrown Can you close this issue? It's resolved now. Thanks!
