### ISSUE TITLE
Sonic spin dash not spinning in sonic the hedgehog 1...

### ISSUE THREAD

**Issue by tonysvo614** [MiSTer-devel/Genesis_MiSTer#172]
Sonic the hedgehog 1...spin dash not on ..

**Comment by Blitzwing1** [comment]
? The first game on the genesis didn't have spin dash. The second game introduced that mechanic.

**Comment by tonysvo614** [comment]
No the 1st game had spin dash....only the sega saturn of sonic 1 has emulated that part correctly

**Comment by Blitzwing1** [comment]
> No the 1st game had spin dash....only the sega saturn of sonic 1 has emulated that part correctly 

There was never an official port of Sonic 1 on the genesis, Sonic 1 didn't have spin dash only fan made roms have added it. 

From Wikipedia on sonic 2:

_The character can jump on enemies to defeat them; the game also introduces a new move, the "spin dash" or "Super Dash Attack", by which the player curls in a ball and spins while stationary_

**Comment by tonysvo614** [comment]
So would running and pushing down cause spin?

**Comment by tonysvo614** [comment]
Ok nevermind I got it...its on off spin  for saturn version
