### ISSUE TITLE
Alien Soldier graphic glitch

### ISSUE THREAD

**Issue by Aquas77** [MiSTer-devel/Genesis_MiSTer#174]
on 32MB ram

Example:
https://clips.twitch.tv/AnnoyingArtisticGarbageBigBrother-M4M-UYSpJDl5GNYI

**Comment by SegaSnatcher** [comment]
I must be blind, where is the glitch located?

**Comment by Aquas77** [comment]
I apologize. This actually occurs in the game. I was referring to the wave that streaks across the horizon.  It just seemed so jank to me I assumed it was wrong. Thanks!
