### ISSUE TITLE
Tiny syntax issue in some files

### ISSUE THREAD

**Issue by grigorovich** [MiSTer-devel/Genesis_MiSTer#177]
Some sources (V and SV) has syntax issues like dat: 
```
case
 ...
endcase; // "semicolon" here is syntax issue for most compilers! 
```
Seldom, but...

**Comment by birdybro** [comment]
Probably never been a problem overall since Quartus 17.0.x is what is used for all cores (save one or two) as is defined in Template_MiSTer.

**Comment by grigorovich** [comment]
Yes I know - its not a critical issue.
 
> Probably never been a problem overall since Quartus 17.0.x
Who knows maybe de-nano will be support in future versions ) joke

But. With that semicolons some simulators works incorrect. Vivado do not warns about that and sometimes synthesized with strange bug... After few hours and investigations i found that issue and note about that here just for future

**Comment by birdybro** [comment]
Yup, I've submitted the pull request, good points! Thanks!

**Comment by birdybro** [comment]
@grigorovich can you close this issue for me? Thanks!

**Comment by grigorovich** [comment]
Ok
