### ISSUE TITLE
OSD Horizontal and vertical position control in Genesis Core

### ISSUE THREAD

**Issue by lencio** [MiSTer-devel/Genesis_MiSTer#191]
I have a problem with the position of the image on the screen of the Genesis Core in several CRT televisions (15hz), using VGA / SCART.
Basically the problem is that on some TVs, the core is off-center to the left, even losing the entire edge.
On other TVs, the core is off-center to the right, or above the screen, losing the upper edge depending on the model.
It is an issue that I have reported in Main_MiSTer and I have been answered (thank you) that it is better to post the problem in each core individually, since it is not possible to implement it at the framework level.
It would be great to have a Horizontal / Vertical position control in the OSD to be able to center the image regardless of the TV used.
I have tested the real machine on different TVs and curiously the image does come out perfectly centered.
I have tried several SONY trinitrons as well, such as SAMSUNG and SANYO models.

**Comment by sorgelig** [comment]
Genesis core is fully matching original HW.

**Comment by lencio** [comment]
> Genesis core is fully matching original HW.

As I have commented in other issues, depending on the TV (VGA / SCART / CRT) in which you start this core, the image does not come out centered. And in some it is only a few lines that are lost and in others more. I think it is an issue that deserves to be reviewed.
Thank you once again for taking your time to respond.

**Comment by sorgelig** [comment]
Just imagine some devs spend a time to make the system as close to original HW as possible. It means normally working TV should output correct video position. Semi-broken, de-tuned TV may give other results. It doesn't mean MiSTer has to deal with such dying TVs.

**Comment by lencio** [comment]
They are not dying, they are different brands, tubes, etc. If you look at the main thread, quite a few people ask for the same thing. Do they all have dying televisions?

**Comment by sorgelig** [comment]
since CRT TV aren't in production at least 10 years, then may be..
