### ISSUE TITLE
Cold rebooting stopped working in Nov-26 release

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Genesis_MiSTer#192]
Probably because new options have been added to the scaler menu (Shadow Masks)?

**Comment by birdybro** [comment]
Yup, same result here. Good catch! Holding the button just delays the soft reboot, text doesn't scroll.

**Comment by sorgelig** [comment]
fixed in 20211127 release

**Comment by bootsector** [comment]
Fixed!
