### ISSUE TITLE
NBA Jam and NBA Jam TE

### ISSUE THREAD

**Issue by Jeebs14** [MiSTer-devel/Genesis_MiSTer#2]
I've tried several different ROMs and NBA Jam TE won't load. All you get are blue jailbars.

NBA Jam was working until the latest build

**Comment by sorgelig** [comment]
NBA still work. It depends on which previous larger ROM you've loaded.

**Comment by sorgelig** [comment]
Both games use special chip in cart.
NBA Jam will work in new release.
NBA Jam TE won't be fixed.
