### ISSUE TITLE
OSD Pause

### ISSUE THREAD

**Issue by HiroiSekai** [MiSTer-devel/Genesis_MiSTer#202]
I ran a search for this and couldn't find it, but is there any chance there could be a toggle added to have the OSD pause the game when active? Most of the other cores currently have this and I've become pre-programmed to bring the menu up. It's helpful for games that don't really have a full pause option too, as the music keeps running in those situations- not great for when you need to take a phone call or something.

Would just be convenient to have, thanks for the consideration!

**Comment by birdybro** [comment]
Most of the console cores don't have this I think, only a few. Pause will probably be added after the core is revisited to fix some of the remaining high-hanging fruit regarding the z80 bus timing. The right person to do that is currently working on the Saturn core.

When pause is added, then this opens the door for savestates to be added as well potentially, so it would be nice.

**Comment by HiroiSekai** [comment]
For sure, I do know that most of the ones I use (NES, GBC, GBC2P, GBA, GBA2P, TGX-16, SGX, and TGX-CD) have it, with the exception of Genesis/MegaCD and SNES. I kinda tend to forget those cores don't have it, and I get reminded when I open the OSD.

So yeah, a bit hopeful it'll happen down the road. 👍

**Comment by sorgelig** [comment]
TurboGrafx-16 has no official pause (which you listed 3 times). It has debug option to pause but it doesn't guarantee reliability as it simply CPU pause. So when you un-pause it it will miss VDP and other events. Correct pause is much more complicated than just pause of CPU. Basically you have pause only in cores supporting save states.

**Comment by birdybro** [comment]
Just going to leave this link here to give perspective to people on how much has to be done to add pause (and savestates) in case they are curious :)

https://github.com/MiSTer-devel/NES_MiSTer/commit/88b8ec80f7d848c2ea99c224698682a6bbae273b
