### ISSUE TITLE
Double Dragon V - The Shadow Falls (USA) [w/ Screenshot]

### ISSUE THREAD

**Issue by KingKannibal** [MiSTer-devel/Genesis_MiSTer#205]
• Format: MD
• Storage: SAMSUNG EVO microSDXC UHS-I U3 100MB/s
• RBF: Genesis_20220326
• Report: Random graphical glitches.
![Screenshot 2022-04-02 09-43-43](https://user-images.githubusercontent.com/69727262/161393808-fc605f26-2a91-4a20-a61c-9b80fa54677a.png)

**Comment by KingKannibal** [comment]
Did more testing with the settings and I forgot I had `CPU Turbo: High`. Lowering it or having it off "fixes" this issue.

**Comment by birdybro** [comment]
Glad you figured it out. Turbo on does introduce bugs and is known to do so. Bugs with cpu turbo happen in software emulators and on modified hardware that have turbo switches which achieve similar results.

**Comment by KingKannibal** [comment]
Yeah, it's sort of obscure too and I would not be surprised if people have accidentally left this setting on but thought it was a core bug instead.

**Comment by birdybro** [comment]
Another one to avoid turbo on. Shining Force II. There's a crash would can also destroy your save near the beginning of the game sort of. It's right when the king of Galam walks down with his soldiers, cpu turbo on will make the screen go wild and if you open the OSD it saves again. Very strange one I remember from awhile back.

**Comment by sorgelig** [comment]
closed as non-issue
