### ISSUE TITLE
Aladdin not animating correctly

### ISSUE THREAD

**Issue by jm33a** [MiSTer-devel/Genesis_MiSTer#23]
There's no walking animation and the down sword isn't appearing.

**Comment by sorgelig** [comment]
Turn off 6 button mode.

**Comment by viciious** [comment]
Excuse my ignorance, but why is the 6 button mode causing so much trouble in different games? Was it the same with the original hardware?

**Comment by sorgelig** [comment]
It's the same as original HW which also gives the same troubles.

**Comment by viciious** [comment]
I believe the original Sega 6-button controller allowed the button mode to be toggled by holding the mode button during the boot. Is it possible with the MiSTer core?

**Comment by sorgelig** [comment]
OSD option "6 button mode" is exactly the same option as toggling the mode on original Sega gamepad.

**Comment by sorgelig** [comment]
6 button mode is used just in few fighting games. For all other games this option must be off.
