### ISSUE TITLE
Mario Lemieux Hockey - Menu impossible to control.. zips through the selections

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/Genesis_MiSTer#232]
As the title suggests, on the main menu for the game where you have your game modes "Exhibition, Tournament" etc.. when you press down on the D-Pad, instead of moving down 1 menu option at a time.. it WHIZZES down through the selection of Modes..

Does the same on Blast-Em Emulator but works fine with Genesis Plus GX on RetroArch.

**Comment by Toryalai1** [comment]
Can you check real hardware?

**Comment by birdybro** [comment]
I can't reproduce this. What kind of controller are you using?

**Comment by davedoc1984** [comment]
1. I have checked Real Hardware and this doesn't happen.
2. I have used both a Dual Shock 4 and a Retrobit Wireless SEGA Arcade Pad and the same behaviour happens.

**Comment by davedoc1984** [comment]
Ahh... I know why

6 Button Mode.... If this is enabled it makes the game go NUTS on the menu.
