### ISSUE TITLE
Scandoubler not working correctly in 20190218

### ISSUE THREAD

**Issue by elexor** [MiSTer-devel/Genesis_MiSTer#25]
Using scandoubled vga output every second line is misaligned.

![20190219_010913](https://user-images.githubusercontent.com/1059357/52956432-4af9fa00-33e3-11e9-911a-376525f80ec0.jpg)

**Comment by James-F2** [comment]
I confirm.
I see the exact same thing.

**Comment by sorgelig** [comment]
will be fixed in next release.
