### ISSUE TITLE
Bimini Run, all audio sounds like it is twice the frequency.

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#26]
All audio in this game sounds like it is playing in twice the frequency and twice the speed.

**Comment by Enforcer831** [comment]
This isn’t caused by the psg. It isn’t used for anything but sound effects. My guess is in is streaming sampled data to the 2612 and there is a timer or busy flag that’s off.

**Comment by James-F2** [comment]
Fixed.

**Comment by birdybro** [comment]
The latest unstable build when jt12 and jt89 were updated by request from @jotego has caused a regression with this issue.

**Comment by jotego** [comment]
If we knew the commit that fixed this issue the first time, we could compare the files.

**Comment by birdybro** [comment]
https://github.com/MiSTer-devel/Genesis_MiSTer/commit/0dadf05344bcd6cc11151cdb446462b2e20df81a - This looks to be the commit that fixed the issue given the timeline, but I am not 100% sure.

**Comment by birdybro** [comment]
This bug occurs on SiDi according to one discord user.

@gyurco does Bimini Run have audio that is too fast on MiST as well? Then updates to JT12 since 2019 have caused a regression.

**Comment by gyurco** [comment]
Reverting this:
https://github.com/jotego/jt12/commit/66eb9ee162e1b1cd3f31f7549af969c7bc191951
fixes the issue

**Comment by birdybro** [comment]
Thank you gyurco! :)

@jotego Will this impact your cores that use jt12 if you change it back to `div_setting <= 2'b11;` on the upstream?

**Comment by jotego** [comment]
The default value for divsetting changes depending on the chip indeed. We can have b'11 for YM2612 and keep b'10 for YM2203. I'll change it.

**Comment by gyurco** [comment]
It's not the default reset value of div_setting, but some other logic change in jt12_div.v (not investigated yet).

**Comment by birdybro** [comment]
> The default value for divsetting changes depending on the chip indeed. We can have b'11 for YM2612 and keep b'10 for YM2203. I'll change it.

Could there be a parameter added for ym2612 mode which passes through to this setting? num ch I see seems to be that kind of parameter right?

**Comment by gyurco** [comment]
Changing the reset value won't help, as the game resets the div setting to 0 by code, which AFAIK shouldn't be allowed on this FM chip.

**Comment by gyurco** [comment]
num_ch is wrong to allow/deny div_setting change, as the comment says, it should be allowed for YM2203 and YM2608, and YM2203 - 3 channels, YM2608 - 6 channels.

**Comment by gyurco** [comment]
This one fixes the game, while it tries to not break the other chips:
https://github.com/gyurco/jt12/commit/a7b6401bca7a268be64df3d08e2aeabc9da90015
