### ISSUE TITLE
Trouble Shooter (U) / Battle Mania (J) - Double Button Mapping

### ISSUE THREAD

**Issue by leeroy1981** [MiSTer-devel/Genesis_MiSTer#27]
Start button is mapped to button C in Battle Mania and the localisation, 'Trouble Shooter'. 

Pressing C button Pauses the Game (and also functions normally, rotating the player forwards and backwards). 

Likewise shoot and bomb are mapped to teh same button. 

I feel this is defintely an issue as it affects both versions of the same game.  (I've alo deleted ini files, reset etc - all other games tested work as expected in this regard).

**Comment by sorgelig** [comment]
turn off 6 button mode!
