### ISSUE TITLE
Genesis digital distortion in Sonic and Knuckles

### ISSUE THREAD

**Issue by elexor** [MiSTer-devel/Genesis_MiSTer#28]
During the cut-scene directly after completing mushroom hill zone act 2 the loud airship that passes by causes some digital distortion that reaches 0.0db dbFS.

Here is a video of it in action. 

https://youtu.be/lPBfM6afN60?t=3m

**Comment by James-F2** [comment]
I confirm.
Digital distortion from HDMI or Analog audio, which reaches 0.0dbFS, that should never happen.
All audio outputs suffer from this so it is something **before** in the core.

I want to add that SNES is also very loud and almost distorting digital inputs on my receiver with some games (Final Fight 3).
Maybe it will be beneficial to lower the entire audio processing in all outputs on the MiSTer by 3db for all cores?

**Comment by sorgelig** [comment]
You can reduce the audio volume on MiSTer if your receiver cannot handle normal 0db volume.

**Comment by James-F2** [comment]
It still distorts with lower MiSTer volume.
The core reachs 0.0dbFS in the digital domain, so truncates date.

**Comment by James-F2** [comment]
@sorgelig 
I wanted to add that two people are working on PSG and Filtering, that includes the audio volume distortion, so you do not need to fix this yourself.

**Comment by sorgelig** [comment]
good!

**Comment by James-F2** [comment]
The PSG should be lowered by 1.5db and the Global volume should be lowered by 3db to prevent distortion in some games.

Maybe you can help with these lines?
https://github.com/MiSTer-devel/Genesis_MiSTer/commit/8c57844812b5158f1289ec42240a19cf5daefd58

**Comment by sorgelig** [comment]
yes

**Comment by James-F2** [comment]
Distortion is still present in 2019.05.03.

**Comment by elexor** [comment]
If you want a quick example zombies ate my neighbors does it a lot. in the
title screens and every time you kill a zombie they explode and the sound
distorts badly.

**Comment by James-F2** [comment]
In Zombies Ate My Neighbors the distortion is part of the actual audio, same on real console.

**Comment by elexor** [comment]
ah my bad. it really sounds like distortion.

**Comment by James-F2** [comment]
@jotego 
We've tested lowering volume before the mixer and apparently it still distorts, so the distortion source is in the FM emulation before the mixer.

**Comment by jotego** [comment]
Are you sure it is the FM and not the PSG?

The FM sound source can operate in a linear region where distortion is not
possible and phase difference in operator signals do not matter.

Or it can operate with higher amplitude or feedback settings where
distortion will occur. In this region the specific phase of the operators
-in some cases- will produce distinct sounds. This can be the problem in
this reported issue.

The specific phases of the operators are documented indirectly in that
clock-cycle C emulator which is a direct C representation of the original
die shot.

I did change a couple of details to fit better that information. I have it
pending to completely compare the two sound sources.

I’ll get to it

**Comment by James-F2** [comment]
Yes, it's from FM.
Tested in emulator where I can disable PSG to verify that the distorting sample is generated by the FM chip.
Can even be the PCM part but I'm not sure.

**Comment by James-F2** [comment]
Here is a reply from Spip on discord:

`
Please tell jotego to try to limit the accumulator output to 9-bit (-256;+255) per channel when summing operators. The distorsion is likely caused by instruments using algo which sums 2,3 or 4 operators configured with TL min or very low (minimal attenuation=max volume). On real ym2612, each channel range is limited but here everything is summed up to 12-bit without channel distinction.
`

**Comment by MP2E** [comment]
This is addressed by #71

**Comment by elexor** [comment]
Glad to see this one fixed thankyou greyrogue.

**Comment by MP2E** [comment]
Turns out this isn't fully addressed by the recent commits, the symptom is just hidden. Spip detailed the right solution above
