### ISSUE TITLE
Afterburner II graphical glitches in sky

### ISSUE THREAD

**Issue by cacophony1** [MiSTer-devel/Genesis_MiSTer#30]
This issue was mentioned in Lon Seidman's recent MiSTer stream:
https://youtu.be/_aEEbKvZQz4?t=3180 (around 53 minutes)

I was able to easily reproduce using the latest MiSTer and Genesis core. Just start up a game and you'll see intermittent glitchy pixels/lines in the sky area.

**Comment by James-F2** [comment]
Glitchy lines?

It is probably related to this bug:
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/22

**Comment by cacophony1** [comment]
Not sure. The segments are much shorter and seem more randomly placed. Give it a try and let me know what you think.

**Comment by James-F2** [comment]
I've tested.
Same random glitchy lines on the real console.
Even worse on the real console.

**Comment by cacophony1** [comment]
Ok, closing. Sorry for the noise.
