### ISSUE TITLE
Overdrive Titan 1 glitches after a reset, or loading the rom again.

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#31]
When loading the core first time or reloading the core, there are **no** glitches in Overdirve 1,, but after a reset or loading the rom again, there are many glitches starting from here:
https://www.youtube.com/watch?v=OGDtViPngi8&feature=youtu.be&t=2m3s

The glitchy screens use raster effects probably involving VSRAM.

**Comment by sorgelig** [comment]
i will check it

**Comment by sorgelig** [comment]
what kind of glitches you mean? Vertical stripes starting from spiral screen?

**Comment by James-F2** [comment]
Yes.
When the thick vertical lines start, they will appear till the end of the demo on various screens.

**Comment by sorgelig** [comment]
it's not related to second rom load. it may appear even on first load. Timings are too tight in this scene.

**Comment by sorgelig** [comment]
New release should fix this issue, although rainbow screen may flicker sometimes.

**Comment by James-F2** [comment]
Unfortunately I have encountered this bug several times with the latest build.

**Comment by James-F2** [comment]
Seems to happen after I "Reset" in the core osd.
Once the bug happens, it will always appear every time, until I restart the core.

**Comment by James-F2** [comment]
@sorgelig 

This rom is used to test if the emulator is accurate:
http://gendev.spritesmind.net/forum/viewtopic.php?t=1291&start=43

Currently only Analogue Mega SG, Exodus and BlastEm emulators pass all test.

**Comment by sorgelig** [comment]
It's well known ROM.

**Comment by henryrizzi** [comment]
Since there's already a thread on Titan Overdrive 1, I figured I'd tag onto this with a few more graphical bugs I encountered while testing the most recent (20190415) release.
The 'we <3 evoke' sequence background animation disappears right after starting.
Last rainbow robot interlace image isn't synced on the far left side of the screen.

I've attached links to the glitches below, apologies for the poor quality:
Heart: https://youtu.be/zrCADSkkkHY
Left pixels: https://youtu.be/3Y6JRnICBCA

**Comment by sorgelig** [comment]
I know about rainbow with robot scene. But i have no issues with 'we <3 evoke' scene background. Titan 1 has several tweaked versions and 2 releases. So may be your version is different?

**Comment by henryrizzi** [comment]
So, I looked into the rom and it's `TiTAN - Overdrive (Rev1.1-106-Final) (Hardware).bin`. After tweaking the settings, the 'we <3 evoke' seen only has issues when the Genesis core is set to EU. I assumed that it had to be set to EU as that was the case for Overdrive 2, but I guess not.
Sorry to bother, but thanks for getting back to me!

**Comment by sorgelig** [comment]
Yeah, Titan 1 is NTSC version While Titan 2 is PAL version.

**Comment by James-F2** [comment]
Seems to be fixed in 20190.05.03 with new VDP.

**Comment by sorgelig** [comment]
ok. then close.
