### ISSUE TITLE
Overdrive Titan 2 - Missing boarders in arcade scene

### ISSUE THREAD

**Issue by the1ross** [MiSTer-devel/Genesis_MiSTer#36]
The Overdrive Titan 2 demo seems to work perfectly except for one small glitch.

In the arcade scene, the knight slashes the side of the screen, then the screen boarder appears, shatters and falls down. How it is supposed to look can be seen here https://youtu.be/gWVmPtr9O0g?t=251

With Mister, not all the boarders appear.

**Comment by sorgelig** [comment]
It's not an issue. This effect is not implemented as it's not used anywhere.
