### ISSUE TITLE
Castle of Illusion graphical glitch

### ISSUE THREAD

**Issue by conradfenech** [MiSTer-devel/Genesis_MiSTer#37]
I would like to report a bug in Castle of Illusion. When on level 2, while walking on a part where there are four leaves next to each other, a line appears glitching as you walk from left to right and back.

**Comment by James-F2** [comment]
That is already reported here:
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/22

**Comment by James-F2** [comment]
This is fixed in the next build.
Can be closed.
