### ISSUE TITLE
Flickering graphics in Alex Kidd in the Enchanted Castle

### ISSUE THREAD

**Issue by henryrizzi** [MiSTer-devel/Genesis_MiSTer#38]
First off, the genesis core is great! I've really been enjoying revisiting the library through MiSTer.

I wasn't able to capture a screenshot of the behavior as the flickering happens so rapidly, but during the rock paper scissors section at the beginning of the game Alex Kidd's hand seems to flicker from rock to the different options when cycling.

It's not a game breaking bug, but it was definitely noticeable during gameplay.
I tested against Genesis_20190307.rbf along with a version compiled from source.

**Comment by henryrizzi** [comment]
Attached is the glitch as it appears on Genesis_20190415.rbf. Not exactly sure what's happening here, but I can at least say the same issue occurs in latest blastem release as well.
Example footage: https://youtu.be/OAJqSzdpSB0

**Comment by James-F2** [comment]
This is a strange one.
I can also se some glitching scanlines during this mini game.

**Comment by gyurco** [comment]
https://github.com/gyurco/fpgagen/commit/1b7ba664e121750ebb960a14c15cef5b8b64d7c3
