### ISSUE TITLE
Slow music - XMen, Toejam & Earl, others?

### ISSUE THREAD

**Issue by ctar** [MiSTer-devel/Genesis_MiSTer#39]
The music seems slower than it should be on these two titles. I'm running the latest core 20190307 and latest Mister & menu. Sound fx and movement seem to be the right speed, just background music. I haven't noticed on other titles. 

Xmen:
https://www.youtube.com/watch?v=cWCUQdKbFNA
Xmen correct speed:
https://www.youtube.com/watch?v=KyZDvaUqBrU

Toejam & Earl:
https://www.youtube.com/watch?v=upE4Kf3ZgRU
Toeman & Earl correct speed:
https://www.youtube.com/watch?v=tWJHhCpc2fU

**Comment by James-F2** [comment]
Why are you using European roms?

**Comment by ctar** [comment]
Indeed, when using the US ROM, the music runs normal speed. Thanks for your reply.
