### ISSUE TITLE
Add quirk for games that don't work with 6 buttons

### ISSUE THREAD

**Issue by Kitrinx** [MiSTer-devel/Genesis_MiSTer#40]
Games like Aladdin are known to not work with 6 button controllers, so controllers should be forced to 3 button with a quirk.

**Comment by sorgelig** [comment]
I would say controller should be set to 3 buttons always. Except for few games.

As for Aladdin it's not an issue at all. Try quickly press and release repeatedly left or right in 3 button mode. You will see the character also will slide instead of run.

**Comment by Kitrinx** [comment]
So add a quirk to enable 6 button mode for games that use it? It's harder to include all (known and unknown) working games rather than exclude the known problem games, that's my only concern with that strategy. I suppose the option could be "auto, 3, 6" so the user can force when needed and use quirks for the known 6 button games.

**Comment by sorgelig** [comment]
I prefer not to change it. 30 years gamers were living with this.
Probably reseting the mode to 3 buttons with every game load (so it won't be possible to save 6-button permanently) could be way, but probably won't be convenient for those who mostly play 6-button games.

I hate the fact that core will choose something unusual hardcoded inside, so i don't like the idea to abuse quirks list.
This is natural incompatibility with 6-button mode presenting on real HW, so i don't see why MiSTer must do something with it.

**Comment by James-F2** [comment]
> This is natural incompatibility with 6-button mode presenting on real HW

All games work perfectly fin with 6button controller on real hardware, besides Golden Axe 2.
The problem is in MiSTer 6button controller emulation.

**Comment by sorgelig** [comment]
that test doesn't show anything useful about controller.

**Comment by sorgelig** [comment]
It think this problem is solved in latest release

**Comment by James-F2** [comment]
Yep, works great.
I've tried many 6button games and the problematic 3button games, all work fine now.
