### ISSUE TITLE
Graphical glitch in Sonic 2 on Sonic Compilation ROM

### ISSUE THREAD

**Issue by goodmaki** [MiSTer-devel/Genesis_MiSTer#41]
I have encountered a graphical glitch which often appears when completing a special stage in Sonic 2 on the "Sonic Compilation ~ Sonic Classics (v1.1)" version of the ROM (CRC 95B5E8D7).  I have not seen this occur on any revision of the standalone cart.

It does not always happen, but during my 'testing' it happened nearly half the time.

Using unmodified Genesis_20190407.rbf.

Screenshot of glitch:
https://i.imgur.com/m1FWNoI.jpg

**Comment by sorgelig** [comment]
It should be fixed already

**Comment by James-F2** [comment]
Seems to be fixed here.

@goodmaki 
Please test again and use the "close issue" button if it is fixed.

**Comment by goodmaki** [comment]
Thanks.  I'll test as soon as I get the chance and update accordingly.

**Comment by goodmaki** [comment]
My mistake in taking this long to update.  I tested this pretty thoroughly and could not reproduce the glitch.  Thank you for your continued efforts.
