### ISSUE TITLE
Robocop vs Terminator 

### ISSUE THREAD

**Issue by cbo2188** [MiSTer-devel/Genesis_MiSTer#43]
Hi.  Not sure if someone saw this or not.  Robocop glides and doesn't walk.  This is on the latest release.

**Comment by goodmaki** [comment]
Can confirm.  Additionally, when Robocop crouches, the screen jitters.

**Comment by sorgelig** [comment]
Did you turn off 6-button mode?

**Comment by goodmaki** [comment]
Setting to 3 button mode fixes it.  Thanks for pointing that out sorgelig.

**Comment by cbo2188** [comment]
Thanks Sorgelig!  That fixed the walking issue.  The top part of the screen does flicker when moving.  Minor though.

**Comment by sorgelig** [comment]
last release should work fine even in 6-button mode
