### ISSUE TITLE
VDP FIFO Test Rom

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#45]
This rom should pass all tests for emulation to be accurate.

http://gendev.spritesmind.net/forum/viewtopic.php?t=1291&start=43

[VDPFIFOTesting.zip](https://github.com/MiSTer-devel/Genesis_MiSTer/files/3142776/VDPFIFOTesting.zip)

**Comment by James-F2** [comment]
@sorgelig 
Can we reopen this?
There is one test that fails still.

**Comment by gyurco** [comment]
It heavily depends on the 68000 bus timings, too, and it differs between MiST and MiSTer, I cannot help more on that.

**Comment by sorgelig** [comment]
I don't think i will work on this issue.
As long as games are fine, it enough for me.
Anyone is welcome to improve.
It may also depends on that fact that MiSTer uses DDR3 for ROM which has floating latency. If it's the case then issue is not worth the switch to SDRAM.

**Comment by Kitrinx** [comment]
It's really impossible to say where and when an accuracy issue of this nature might impact a game, given the size of the library and the length of the games, possibly in minor ways that are hard for a user base of our size to catch. I think it would bring everyone more peace of mind to resolve it.

**Comment by gyurco** [comment]
68k bus timing can affect the stabilization methods of direct color dma demos (#89)

**Comment by James-F2** [comment]
All pass with SDRAM.
Amazing work Sorgelig and srg320!

**Comment by sorgelig** [comment]
Bus timings is still work in progress.
