### ISSUE TITLE
Graphical glitch in Rocket Knight Adventures (release build 2019.05.03)

### ISSUE THREAD

**Issue by loloC2C** [MiSTer-devel/Genesis_MiSTer#46]
I've found an issue with the Genesis core (build 2019.05.03 release and the previous one)

In the 2nd part of Stage 2 there are some chains displayed that scrolls vertically. Seems like these chains are composed of 2 tiles wide elements that are supposed to scroll together vertically however there is some one tile shift (see the below screenshot)

![image](https://user-images.githubusercontent.com/44382811/57166357-392cce00-6dfa-11e9-901f-f31c4e2d6779.png)

A video of the correct effect can be found there (at 11:38) : https://www.youtube.com/watch?v=TlDYcXv9yM0

**Comment by James-F2** [comment]
Sprite position is misaligned.

**Comment by James-F2** [comment]
Above bug seems to use first left sprite as 24 pixel wide sprite size, while it should use 16 pixel wide.
The next tiles are 16 pixel wide, but since the first one is 24, the rest are misaligned,, and the last tile on screen is 8 pixel wide.

First left sprite 24, then 16:
![rka mister](https://user-images.githubusercontent.com/31185814/57174248-99e0f880-6e44-11e9-9fbf-97491d6a133c.png)

How it should look, all 16:
![RKA 320x224](https://user-images.githubusercontent.com/31185814/57174210-09a2b380-6e44-11e9-9e32-0e9a9e4f741e.png)

**Comment by sorgelig** [comment]
how it was in previous release?

**Comment by James-F2** [comment]
That is probably a bug in Vertical scrolling, it is only 16 pixel wide.
Register $0B.

All info here:
https://segaretro.org/Sega_Mega_Drive/Scrolling

**Comment by James-F2** [comment]
I should add that that problem varies with the position of the character on screen, so in some positions the spikes align correctly.
Note that the screen moves with the character and the vertical scrolling 'bars' align differently.

**Comment by gyurco** [comment]
Please try this patch:
https://github.com/gyurco/fpgagen/commit/257c887fbbbba7f170c3cf6338873ec479b5f436

**Comment by James-F2** [comment]
Can't compile.
![DualPortRAM](https://user-images.githubusercontent.com/31185814/57198317-ed089780-6f79-11e9-937e-fcd6805794a2.png)

**Comment by gyurco** [comment]
Well, I found it works in some cases, but not the best. Will do a better version of the patch.

**Comment by James-F2** [comment]
It is aligned when I'm in the most left part of the screen, but as soon as I move to the right the vertical bars are "shuffling" and become misaligned again.

**Comment by gyurco** [comment]
This works better in the simulator:
https://github.com/gyurco/fpgagen/commit/7828c3a91ff9129e73f6e8522c2ab0e57887e4ac

I'll do more testing with some known 2-column VSCROLL games tomorrow.

**Comment by James-F2** [comment]
Thank you.

Here is a good thread to read about vertical scrolling problem on the real Genesis:
http://www.sega-16.com/forum/showthread.php?31309-When-did-they-fix-the-column-scroll-bug

**Comment by gyurco** [comment]
Yes, I know about the "left-column VSCROLL bug". It can be seen at Kawasaki Superbike Challenge for example. Interestingly, some games are not aware of this original bug, and displays correctly without implementing it (see Gynoug earthquake at stage1 in BlastEm).

**Comment by sorgelig** [comment]
@gyurco, 
to our discussion: i forgot i had this tweak:
```
vscroll_index := BGB_COL(5 downto 1) + 1;
```
same for BGA
only with this tweak Gynoug looks correct in earthquake. Without +1 it has misplaced first column. So, it's definitely VSRAM is shifted..

**Comment by gyurco** [comment]
You shift VSRAM index with this change wrongly. Of course there will be no bad left column (since -1 will be 0 - same as using VSRAM(0) and (1) for the partial column), but you destroy the rightmost one (and every other mid-screen will use the wrong index).

**Comment by gyurco** [comment]
Here's my final patch:
https://github.com/gyurco/fpgagen/commit/290b2ba8ad8b9f8a91bdadc5f6316943537e0794
The AND'ing of VSRAM(38) and (39) can be tweaked, but this is what the original hardware supposed to do (according to Eke-Eke at Spritesmind forum).

**Comment by sorgelig** [comment]
i've tried ANDing myself - result was awful
will check your patch

**Comment by sorgelig** [comment]
i'm more toward the VSRAM(0) and VSRAM(1) than ANDing. It has less artifacts :)

**Comment by gyurco** [comment]
Uncomment the appropriate option :) But then the first two chains will always move together in Rocket Knight (not the biggest issue in the world - maybe not even an issue, at least they won't flicker).

**Comment by sorgelig** [comment]
yes, ANDed version equally awful in both Gynoug and Rocket Knight while 0/1 is good in both games. I will add an input port for VDP to select it. 
I'm in process of unification of VDP, so should be ready soon.

**Comment by sorgelig** [comment]
About why it's 0 in H32: I believe the internal logic prevents to read the VSRAM >63 in H32 mode and read 0 instead. So, the same AND logic applies for H32 but with both values 0.

**Comment by James-F2** [comment]
Compiled and tested.
It is fixed.
Well done!

**Comment by James-F2** [comment]
@sorgelig 
I see gyurco made another small fix: https://github.com/gyurco/fpgagen/commit/fbb4ac29a736bd713181c858b069001ac8344795

Did you choose 'nicer effect' or 'HW original' in MiSTer core?

**Comment by sorgelig** [comment]
I use nicer effect. There is no point to use awfully looking effect.

**Comment by gyurco** [comment]
AFAIK Genesis 3 has the "nicer" look, too. That counts as original HW.

**Comment by sorgelig** [comment]
considered as fixed
