### ISSUE TITLE
Toggling menu item changes value of element above

### ISSUE THREAD

**Issue by commonbreed** [MiSTer-devel/Genesis_MiSTer#48]
Beneath the "Auto Region" option, all menu items, when toggled, change the value of the menu item located one line above.

In addition to this, as a result of there being no item below "Auto Region", but above "Load Backup RAM", interacting with the "Load Backup RAM" option does nothing.

Genesis v190510
Firmware HPS190304

**Comment by sorgelig** [comment]
you need to update HPS to latest

**Comment by commonbreed** [comment]
Ah, didn't notice the main image was so old! Now ROMs aren't booting at all, but I'll dig a little deeper to find the problem.
