### ISSUE TITLE
General core slow-down since early 2018

### ISSUE THREAD

**Issue by commonbreed** [MiSTer-devel/Genesis_MiSTer#49]
Using the 190510 core, I'm encountering (what feels to be - not measured) around 10% slowdown which makes fast-sequence games such as Sonic irritating to play.

After trying some cores from early 2018, although the sound isn't accurate, as well as some other issues, the speed seems to be much closer to what I'd expect.

**Comment by jotego** [comment]
Are you sure you’re playing with the right regional setting?

**Comment by commonbreed** [comment]
@jotego Yes, I'm sure. The game gives a notice if the wrong region is being used, and I've checked that the region is correct.

**Comment by sorgelig** [comment]
Sonic is multi-region game. It works in all regions and of course it's slower when EU region is selected. 
Earlier version of Genesis supported only US region.
Rename your ROM to extension .gen or .bin and it will work faster.
