### ISSUE TITLE
Aladdin / Lion King music sounds off

### ISSUE THREAD

**Issue by the1ross** [MiSTer-devel/Genesis_MiSTer#5]
The music for these two games (and possible other Virgin / Disney games), sounds off when compared to original hardware.

**Comment by jeffgerstmann** [comment]
I noticed another "audio sounds off" issue with Bimini Run (USA).

There's a little bit of speech in the first few seconds of the game ("Kenji, come in!") and it's playing too fast and high-pitched in the 20181210 version of the core. Music seems to be playing fast and/or high as well, but I can't confirm 100%.

**Comment by James-F2** [comment]
It sounds off because there is no Lowpass filtering and PSG sound if wrong.
The fixes are almost done by two people who are working on it, and will show up as pull-requests soon.

**Comment by the1ross** [comment]
Hi 

I changed the settings in the initial file and the picture is now perfect but the sound does feel a little off when compared to HDMI. Overall I'm happy and will wait for further updates.

Thanks again. 
On Monday, 18 February 2019 James-F2 <reply@reply.github.com> wrote:

It sounds off because there is no Lowpass filtering and PSG sound if wrong.
The fixes are almost done by two people who are working on it, and will show up as pull-requests soon.

**Comment by the1ross** [comment]
Sorry it took so long, but I've tried them again and they sound very accurate now. Thank you.
