### ISSUE TITLE
[audio] Streets of Rage - High Hat sound changes in Keep the Groovin'

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/Genesis_MiSTer#53]
You can reproduce this by going into Sound Test, under Options, and selecting "Round 4". The high hat sound will shift around, when on a Genesis model 1 or model 2, it will have the same sound each measure.

Here is an example of how it plays on a Genesis model 1 VA3
https://youtu.be/5Lp0GJNTRV0?t=801

As an additional note, I know the projects have *nothing* to do with each other, but the Mega SG also had a very similar problem with this same song. kevtris mentioned in Discord that it was to do with the Phase not being reset correctly. I do not know if this applies to the MiSTer but am sharing this information in case it does.

thanks!

**Comment by jotego** [comment]
Hi, I’m the developer of JT12, the sound module used.

I am aware of this issue. It is evidence that Kevtris is probably using
JT12 illegally in a closed source product.

At some stage I may fix it. It does imply a lot of effort for a very small
return.

Thanks for reporting it.

**Comment by SegaSnatcher** [comment]
Any updates/plans to look into this?  This fix would be highly appreciated.

**Comment by jotego** [comment]
It is still in work queue. It may be either end of this month or next month
when I get to it.

**Comment by sorgelig** [comment]
Is it already fixed?

**Comment by MP2E** [comment]
Unfortunately no, I have tested with the latest changes. I spoke to Nukeykt, writer of Nuked-OPN2, and he stated he had a similar bug that had to do with Operator keyon logic.

However, I traced through jt12_kon and did not see a problem. Not sure where the issue could be

**Comment by jotego** [comment]
It probably is a difference in the phase value of each operator. Although
for small amplitudes phases are not important, the synthesizer produces non
linear effects for large amplitudes used for modulation. For JT51 I had
measurements of each modulation combination so I was able to adjust
everything in the pipeline to get exactly the same non linear effects. For
JT12 I didn’t have that. It can be fixed without major changes but it needs
a few hours of work and is not my top priority now.

**Comment by SegaSnatcher** [comment]
Greyrogue recently applied a test fix and it sounds great to me now.

**Comment by James-F2** [comment]
Sounds fixed with https://github.com/MiSTer-devel/Genesis_MiSTer/pull/84

**Comment by MP2E** [comment]
Indeed, this is addressed. Thanks again @greyrogue !
