### ISSUE TITLE
[audio] Rocket Knight Adventures - Volume too high for flames in Stage 1-2

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/Genesis_MiSTer#54]
In Rocket Knight Adventures, if you simply leave the game on the title screen for a few seconds, it will play a demo. Once the demo shows Stage 1-2, inside the Castle, the player will move to an area where large flames shoot horizontally across the screen. At this point, the flame sound will distort very badly because it is seemingly played at too high of a volume. I have compared this to a real Genesis model 1 VA3 and a Genesis model 2 with megaamp, and in both those cases, there was no audible clipping.

Hope this helps, thanks!

**Comment by James-F2** [comment]
Similar distortion can be heard in this issue report:
https://github.com/MiSTer-devel/Genesis_MiSTer/issues/28

**Comment by MP2E** [comment]
This is addressed by #71
