### ISSUE TITLE
Pier Solar won't get past 1st screen

### ISSUE THREAD

**Issue by esmith13** [MiSTer-devel/Genesis_MiSTer#6]
Pier Solar won't load beyond the initial disclaimer screen.

I know it is an unlicensed game created long after the Genesis was discontinued but since it does run on real hardware I thought it worth noting here.

Side Note: I am not using SDRam add on board. Perhaps this rom it too large and needs it? Does this core even support the SDRam board if present?

EDIT: Now have SDRam board and game still gets stuck on first screen (disclaimer screen).

**Comment by henryrizzi** [comment]
Looks like Pier Solar is running with the most recent commits, but that hasn't been cut for release yet. If you would like to build from source, it should run as expected at least through the opening and a bit after (haven't tested further than that).

**Comment by Kitrinx** [comment]
this is probably resolved now

**Comment by James-F2** [comment]
Can be closed.
