### ISSUE TITLE
Most accurate YM2612 code

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#60]
* This is not an issue but a recommendation.

Alexey Khokholov (nukeykt) has the most accurate YM2612 (OPN2) and PSG code in c.
https://github.com/nukeykt

His work is in DOSBox, Genesis Plus GX, and more.

**Comment by sorgelig** [comment]
This has nothing to do with FPGA.
You can tell the Jotego about this code, but i think he already knows it.

**Comment by jotego** [comment]
Yes, I know about that work. It’s actually very good. I made a change to
the envelope generator based on that code a while ago.

There are a couple of issues pending to be fixed and I may consult that
reverse engineering effort when I work on them.
