### ISSUE TITLE
Sonic 2: bottom two lines of pixels contain random junk

### ISSUE THREAD

**Issue by c0d3h4x0r** [MiSTer-devel/Genesis_MiSTer#65]
![1C41F515-660B-483C-901D-5A2C26676F07](https://user-images.githubusercontent.com/24398884/60319625-df451200-992b-11e9-9f8f-ef324e6051f8.jpeg)

**Comment by sorgelig** [comment]
i think it's how supposed to be.
At least blastem emulator also shows the same.

**Comment by MP2E** [comment]
@sorgelig is correct, this is how the game behaves on hardware. Here is a recording from my Sega Genesis Model 2, motherboard VA1.8

https://streamable.com/bp2ou

**Comment by c0d3h4x0r** [comment]
Interesting... I guess my CRT TV back in the day must have hidden that in the overscan area.  Sorry for the false alarm!

**Comment by SegaSnatcher** [comment]
What's interesting is this original hardware glitch is fixed when you add Sonic & Knuckles cart.
