### ISSUE TITLE
Sync issues with HDMI PC Monitor

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/Genesis_MiSTer#75]
Seems to have started happening with the direct_video change and is unfortunately not addressed by the latest commit for me, when I leave the genesis core running it now randomly blanks out and resyncs on my monitor every few seconds, with direct_video set to 0

**Comment by MP2E** [comment]
Maybe a metastability issue? One build I made with a different seed actually resyncs more often. Will try to keep making builds with different seeds

**Comment by MP2E** [comment]
After building a few different builds with random seed numbers, I got one that is fully stable. I guess this is a metastability issue. Closing

**Comment by jotego** [comment]
Hi @MP2E 

It would be interesting to know the path that created the issue. Sometimes it is easy enough to add a register stage and solve the timing problem in design, rather than with seed values.

**Comment by MP2E** [comment]
All stability issues seem to be gone with the latest commits, but I will be more thorough in the future
