### ISSUE TITLE
Wrong pixel line in Snow Bros intro

### ISSUE THREAD

**Issue by vanfanel** [MiSTer-devel/Genesis_MiSTer#77]
Hi there,

I found this error on Snow Bros story/intro sequence: you can clearly see a red/blue line of pixels during all the intro, on the upped part of the screen.
Maybe its a small VDP problem?

**Comment by gyurco** [comment]
If it's about the first line, then:
https://github.com/gyurco/fpgagen/commit/f698d349e18aa56f2a7b2c788e5333c367371d19
