### ISSUE TITLE
Sync Timing Issue with Extron

### ISSUE THREAD

**Issue by leeroy1981** [MiSTer-devel/Genesis_MiSTer#78]
First off, I know this may not be classed as an issue as I'm using an additional piece of equipment. An Extron 160xi. (I'm happy to buy an Extron for any developer who wishes to check this issue though). 

Versions later than Genesis_20190627 do not provide a stable picture through an Extron device. I've confirmed with two other users using different Extrons on the Facebook group and they both have the same issue. 

If I understand correctly some games switch resolutions. (The Sega license screen is always garbled FWIW). 

Thunder Force IV uses 320x224@59.9 Hz, 15.70 kHz for gameplay and title screen (Garbled picture)
and 256x224@59.9 Hz for the Highscore screen (Perfect picture)

Tested with  Extron 109xi / Extron 160xi / Extron 164xi 

Version Genesis_20190627 (and all proceeding versions work 100% okay) all later versions have showing garbled graphics when in game resolution switching. 

I'm happy to send an Extron to any dev who wants to check it out.

**Comment by sorgelig** [comment]
"int shipping" is twice higher :)

![image](https://user-images.githubusercontent.com/917089/64844669-fe099980-d63a-11e9-870c-63f5c6bc67e3.png)

**Comment by leeroy1981** [comment]
No problem at all. Which paypal address would you like me to send to? Thanks.

**Comment by sorgelig** [comment]
https://github.com/MiSTer-devel/Main_MiSTer/wiki/Donate

**Comment by leeroy1981** [comment]
Just sent the money and left a clear note that it's for the Extron purchase. :)

**Comment by sorgelig** [comment]
I've received the Extron and already identified the source of problem. HSync is too long. Actually it's weird problem. I understand when HSync can be too short for some displays to detect it. But too long...

**Comment by paulb-nl** [comment]
Then a real Genesis should also have problems with these Extron because the HSync length was the same as real Genesis.

**Comment by sorgelig** [comment]
@paulb-nl did you measure the HSync from the core? Didn't it fall into slow clock area? so could be much longer than needed.

**Comment by paulb-nl** [comment]
James-F did the measurements comparing MiSTer and Genesis when we were adjusting HSync here: [https://github.com/MiSTer-devel/Genesis_MiSTer/issues/66#issuecomment-509186426](https://github.com/MiSTer-devel/Genesis_MiSTer/issues/66#issuecomment-509186426)

HSync length on a real Genesis is 5.75us in 320x224 because of the slow clock area.

**Comment by sorgelig** [comment]
i've played a bit with hsync length. 4.7us is ok. 5.0us already no picture from extron.
Is it possible that different Genesis models have different hsync length?

**Comment by James-F2** [comment]
Has it been confirmed that this Extron can handle the real genesis hardware?

**Comment by James-F2** [comment]
@sorgelig 

constant` HSYNC_START_H32        : integer := H_DISP_START_H32 + 0;
constant HSYNC_START_H40        : integer := H_DISP_START_H40 + 7;

constant HSYNC_END_H32          : integer := H_DISP_START_H32 + 24;
constant HSYNC_END_H40          : integer := H_DISP_START_H40 + 30;

**Comment by sorgelig** [comment]
That works fine. Thanks. 
It's included in my last commit (forgot to split it from Z80 wait state fix).

**Comment by sorgelig** [comment]
Original issue is fixed.
