### ISSUE TITLE
"Blast Processing" test rom flickers

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#89]
Don't mind the name, it's just a 68k+VDP timing test rom.

Test ROM:
https://drive.google.com/file/d/1Ag-J_smY75mUGAIL3J1VHwTVdmFWbyL0/view

This should display a solid image like here:
https://youtu.be/_ZCQ6kN9Ie0?t=14m43s

**Comment by bootsector** [comment]
:scream: :tophat:

**Comment by James-F2** [comment]
Works with SDRAM fix.
Well Done!
