### ISSUE TITLE
"Game No Kandume Otokuyou (Japan) (Sega Channel)" game not working

### ISSUE THREAD

**Issue by Kikusui1** [MiSTer-devel/Genesis_MiSTer#90]
As per title "Game No Kandume Otokuyou (Japan) (Sega Channel)" doesn't work. The game initially loads as expected. But upon selecting one of the Mini games the MiSTer then goes to a black screen. This happens when selecting any mini game. After a minute or so I then get what can be described as "white noise" or static.

**Comment by gyurco** [comment]
From BlastEm:

> 31c66bd13abf4ae8271c09ec5286a0ee0289dbbc {
        #Designed to run on Sega Channel hardware which is RAM-based
        #writes to the this RAM qutie a bit to select games
        name Game no Kanzume Otokuyou
        map {
                0 {
                        device ROM
                        last 3FFFFF
                        writeable yes
                }
        }

(Part of)  the ROM is writeable.

**Comment by sorgelig** [comment]
thanks for info! It's new addition.
In blastem 0.51 i've used, there is no mention about this game.

**Comment by birdybro** [comment]
Going through and testing out some of these old issues that are still open. This game works fine for awhile now. This issue can be closed @Kikusui1 :)
