### ISSUE TITLE
Composite Blending - moving the image 1 pixel to the right

### ISSUE THREAD

**Issue by James-F2** [MiSTer-devel/Genesis_MiSTer#96]
on CRT and LCD.

@Kitrinx 
This is mainly for you since you know where to fix that.

**Comment by sorgelig** [comment]
it's because HSync/VSync not delayed together with picture in blending module.

**Comment by sorgelig** [comment]
Should be fixed in latest commit.
Due to nature of blending it can look like picture is still shifting a little.
But should be better now.

**Comment by sorgelig** [comment]
One more update for blending. Now it doesn't move/glitch when switched.

**Comment by James-F2** [comment]
Fixed but analog video is moved again.
Soon we'll have no more hsync room to adjust with.
