### ISSUE TITLE
Option to run ROMs from SDRAM instead of DDR3?

### ISSUE THREAD

**Issue by bootsector** [MiSTer-devel/Genesis_MiSTer#98]
I've tried the TG16 core with the option for loading ROMs to SDRAM instead of the DDR3 and games got much more stable (no issues with Magical Chase, for example).

How hard would it be to add a similar option to the Genesis core? I have the impression this might solve most of the "timing related" bugs "automagically"? 🤔

**Comment by sorgelig** [comment]
Such option may appear later

**Comment by James-F2** [comment]
I wonder if the new SDRAM pll method will be more accurate for this edge case: https://github.com/MiSTer-devel/Genesis_MiSTer/issues/89

**Comment by sorgelig** [comment]
yes, sdram will fix that. But that's not game. And no games relay (or can relay) on that

**Comment by James-F2** [comment]
Amazing work!
Can be closed.
